// A short list of the most commonly searched local-business niches, shown as
// tap-to-select pills so the common case never requires typing or scrolling
// through the full 1,086-entry SCIAN catalog (see components/project-setup/
// keyword-picker.tsx). Deliberately broad, generic Spanish category words —
// DENUE's free-text search matches these as a substring across every SCIAN
// clase título that contains them, so "restaurantes" surfaces every
// restaurant subtype (tacos, mariscos, comida corrida, etc.) in one search
// rather than the single exact clase the full-catalog combobox would pick.
export const QUICK_PICK_KEYWORDS = [
  "Restaurantes",
  "Cafeterías",
  "Bares",
  "Panaderías",
  "Farmacias",
  "Ferreterías",
  "Papelerías",
  "Tiendas de ropa",
  "Zapaterías",
  "Salones de belleza",
  "Barberías",
  "Gimnasios",
  "Talleres mecánicos",
  "Veterinarias",
  "Consultorios dentales",
  "Consultorios médicos",
  "Despachos jurídicos",
  "Despachos contables",
  "Hoteles",
  "Tintorerías",
  "Ópticas",
  "Florerías",
  "Joyerías",
  "Tiendas de conveniencia",
  "Supermercados",
  "Guarderías",
  "Escuelas",
  "Gasolineras",
  "Pizzerías",
  "Pastelerías",
  "Neverías",
  "Tortillerías",
  "Carnicerías",
  "Fruterías",
  "Lavanderías",
  "Cerrajerías",
  "Vulcanizadoras",
  "Refaccionarias",
  "Lavado de autos",
  "Estacionamientos",
  "Inmobiliarias",
  "Aseguradoras",
  "Notarías",
  "Agencias de viajes",
  "Imprentas",
  "Mueblerías",
  "Tiendas de electrónica",
  "Estudios fotográficos",
  "Spas",
  "Estudios de tatuajes",
  "Fisioterapia",
  "Funerarias",
];
