// Generated by scripts/generate-scian-catalog.mjs — do not edit by hand.
export interface ScianSector {
  code: string;
  title: string;
}

export const SCIAN_SECTORS: ScianSector[] = [
  {
    "code": "11",
    "title": "Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza"
  },
  {
    "code": "21",
    "title": "Minería"
  },
  {
    "code": "22",
    "title": "Generación, transmisión, distribución y comercialización de energía eléctrica, suministro de agua y de gas natural por ductos al consumidor final"
  },
  {
    "code": "23",
    "title": "Construcción"
  },
  {
    "code": "31-33",
    "title": "Industrias manufactureras"
  },
  {
    "code": "43",
    "title": "Comercio al por mayor"
  },
  {
    "code": "46",
    "title": "Comercio al por menor"
  },
  {
    "code": "48-49",
    "title": "Transportes, correos y almacenamiento"
  },
  {
    "code": "51",
    "title": "Información en medios masivos"
  },
  {
    "code": "52",
    "title": "Servicios financieros y de seguros"
  },
  {
    "code": "53",
    "title": "Servicios inmobiliarios y de alquiler de bienes muebles e intangibles"
  },
  {
    "code": "54",
    "title": "Servicios profesionales, científicos y técnicos"
  },
  {
    "code": "55",
    "title": "Dirección y administración de grupos empresariales o corporativos"
  },
  {
    "code": "56",
    "title": "Servicios de apoyo a los negocios y manejo de residuos, y servicios de remediación"
  },
  {
    "code": "61",
    "title": "Servicios educativos"
  },
  {
    "code": "62",
    "title": "Servicios de salud y de asistencia social"
  },
  {
    "code": "71",
    "title": "Servicios de esparcimiento culturales y deportivos, y otros servicios recreativos"
  },
  {
    "code": "72",
    "title": "Servicios de alojamiento temporal y de preparación de alimentos y bebidas"
  },
  {
    "code": "81",
    "title": "Otros servicios excepto actividades gubernamentales"
  },
  {
    "code": "93",
    "title": "Actividades legislativas, gubernamentales, de impartición de justicia y de organismos internacionales y extraterritoriales"
  }
];
